#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Measure admitted raw streams and executable fixtures under directive 2.2.

The manifests bind provenance, exact bytes and SHA256; payloads are never
printed. Missing real Codex scenarios remain explicit, even if tests pass.
"""
import argparse
import collections
import hashlib
import json
import pathlib
import subprocess
import sys

MAX_LINE = 1048576
SOURCES = {"codex-app-server", "gemini-acp", "mcp-stdio"}


def digest(path):
    result = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(65536), b""):
            result.update(chunk)
    return result.hexdigest()


def lines(path):
    """Yield length and bounded prefix; drain oversized lines without retaining them."""
    with path.open("rb") as stream:
        while True:
            prefix = stream.readline(MAX_LINE + 2)
            if not prefix:
                return
            length = len(prefix)
            tail = prefix
            suffix = prefix[-2:]
            while tail and not tail.endswith(b"\n"):
                tail = stream.readline(65536)
                length += len(tail)
                suffix = (suffix + tail)[-2:]
            complete = bool(tail and tail.endswith(b"\n"))
            # For incomplete lines, prefix may still be the entire bounded input.
            if complete:
                length -= 1
                if prefix.endswith(b"\n"):
                    prefix = prefix[:-1]
            strip_cr = complete and suffix == b"\r\n"
            if strip_cr:
                length -= 1
                if len(prefix) == length + 1:
                    prefix = prefix[:-1]
            yield length, prefix[:MAX_LINE + 1], complete


def audit(manifest_path, probe):
    index = json.loads(manifest_path.read_text())
    if index.get("schema_version") != 2:
        raise ValueError("unsupported corpus manifest schema")
    streams, manifests = [], {}
    for source in sorted(SOURCES):
        child = manifest_path.parent / source / "MANIFEST.json"
        if not child.exists(): continue
        manifest = json.loads(child.read_text()); manifests[source] = manifest
        for item in manifest["streams"]:
            streams.append({**item, "path": source + "/" + item["path"]})
    problems = []
    counts = collections.Counter(item["source"] for item in streams)
    for source, minimum in (("mcp-stdio",50),("codex-app-server",50),("gemini-acp",20)):
        if counts[source] < minimum: problems.append(f"streams_missing: {source} {counts[source]}/{minimum}")
    if not manifests.get("codex-app-server",{}).get("approvals_declined"):
        problems.append("codex_turn_and_declined_approval_not_admitted")
    report = {"schema_version": 2, "directive_revision": "2.2", "scope": "corpus-measurements",
              "declared_streams": len(streams), "counts": dict(counts),
              "problems": problems, "streams": [],
              "jsonrpc_chunk_invariance": "see differential report generated by make test"}
    seen_paths, seen_hashes, sources = set(), set(), set()
    base = manifest_path.parent.resolve()
    for item in streams:
        relative = item["path"]
        path = (base / relative).resolve()
        if not path.is_relative_to(base) or path == base:
            raise ValueError("capture path escapes corpus directory")
        if path in seen_paths:
            raise ValueError("capture declared twice")
        seen_paths.add(path)
        source = item["source"]
        if source not in SOURCES:
            raise ValueError("unknown capture source")
        if item.get("anonymized") is not False:
            raise ValueError("raw captures must not be anonymized")
        if not item.get("tool") or not item.get("captured_at") or not item.get("provenance"):
            raise ValueError("capture provenance fields missing")
        sha = digest(path)
        if sha != item["sha256"]:
            raise ValueError("capture sha256 mismatch")
        # Identical descriptor output across distinct scripted sessions is valid.
        seen_hashes.add(sha)
        sources.add(source)
        metrics = {"path": relative, "source": source, "sha256": sha,
                   "bytes": path.stat().st_size, "lines": 0, "max_line_bytes": 0,
                   "blank_lines": 0, "preamble_lines": 0, "over_limit_lines": 0,
                   "orphan_bytes": 0, "non_integer_numbers": 0,
                   "non_integer_ids": 0, "non_integer_error_codes": 0,
                   "missing_jsonrpc_marker": 0,
                   "parse_reasons": collections.Counter(),
                   "writer_reasons": collections.Counter(), "exceptions": []}
        started = False
        for length, prefix, complete in lines(path):
            metrics["max_line_bytes"] = max(metrics["max_line_bytes"], length)
            if not complete:
                metrics["orphan_bytes"] = length
                break
            metrics["lines"] += 1
            if length > MAX_LINE:
                metrics["over_limit_lines"] += 1
                metrics["parse_reasons"]["LIMIT"] += 1
                continue
            if length == 0:
                metrics["blank_lines"] += 1
                continue
            if source == "gemini-acp" and not started:
                # Existing runtime adapter considers both { and [ candidates.
                if not prefix.lstrip(b" \t\r\f\v").startswith((b"{", b"[")):
                    metrics["preamble_lines"] += 1
                    continue
            started = True
            try:
                envelope = json.loads(prefix)
                if isinstance(envelope, dict) and envelope.get("jsonrpc") != "2.0":
                    metrics["missing_jsonrpc_marker"] += 1
            except (ValueError, UnicodeError): pass
            result = subprocess.run([str(probe)], input=prefix,
                                    stdout=subprocess.PIPE, check=True)
            observation = json.loads(result.stdout)
            metrics["parse_reasons"][observation["parse"]] += 1
            if observation["parse"] == "OK":
                metrics["writer_reasons"][observation["writer"]] += 1
                metrics["non_integer_numbers"] += observation["non_integer_numbers"]
                metrics["non_integer_ids"] += observation["non_integer_id"]
                metrics["non_integer_error_codes"] += observation["non_integer_error_code"]
            legacy = "mcp" if source == "mcp-stdio" else "codex"
            if observation[f"{legacy}_accepted"] and (
                    observation["parse"] != "OK" or not observation[f"equal_{legacy}"]):
                metrics["exceptions"].append({"line": metrics["lines"], **observation})
        report["streams"].append(metrics)
    for source in sorted(SOURCES - sources):
        problems.append(f"source_missing: {source}")
    report["corpus_prerequisite"] = "incomplete" if problems else "declared_and_measured"
    report["provenance_review"] = "recorded_sources_with_fixture_labels"
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=pathlib.Path, required=True)
    parser.add_argument("--probe", type=pathlib.Path, required=True)
    parser.add_argument("--report", type=pathlib.Path, required=True)
    args = parser.parse_args()
    try:
        report = audit(args.manifest, args.probe.resolve())
    except (OSError, ValueError, KeyError, TypeError, subprocess.CalledProcessError) as error:
        print(f"corpus audit failed: {type(error).__name__}", file=sys.stderr)
        return 2
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, ensure_ascii=True, indent=2, sort_keys=True) + "\n")
    print(json.dumps({"corpus_prerequisite": report["corpus_prerequisite"],
                      "declared_streams": report["declared_streams"],
                      "problems": report["problems"]}))
    return 1 if report["problems"] else 0


if __name__ == "__main__":
    sys.exit(main())
